//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRentCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Id_driver { get; set; }
        public string Name { get; set; }
        public string DNI { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Number_card { get; set; }
    }
}
