//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRentCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int Id_office { get; set; }
        public Nullable<int> Id_city { get; set; }
        public string Address { get; set; }
        public string Postal_code { get; set; }
        public string Telephone { get; set; }
        public string Code { get; set; }
    }
}
