//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRentCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id_vehicle { get; set; }
        public Nullable<int> Id_office { get; set; }
        public string Patent { get; set; }
        public string Group { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public Nullable<int> Number_doors { get; set; }
        public Nullable<int> Number_passengers { get; set; }
        public string Capacity_vault { get; set; }
    }
}
